#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ $(git symbolic-ref --short HEAD) = "master" ] || [ $(git symbolic-ref --short HEAD) = "dev" ]; then echo "Error: Cannot push to master or dev branch" && exit 1; fi
